language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.3
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - yes | sdkmanager "platforms;android-30"
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew build
